```{r, echo=FALSE, include=FALSE}
# Create a choropleth map of the United States that compares the average covered charges to the average total payments
library(dplyr)
hospital.data <- read.csv("data/hospital_data.csv", stringsAsFactors = F)
hospital.data.state <- hospital.data %>%
  select(Provider.State, Average.Covered.Charges, Average.Total.Payments) %>% 
  group_by(Provider.State) %>% 
  summarize(State.Covered.Charges = mean(as.numeric(gsub("\\$", "", Average.Covered.Charges)) / as.numeric(gsub("\\$", "", Average.Total.Payments))))
source("scripts/choropleth.r")
state.choropleth <- makeStateChoropleth(hospital.data.state)
```
#State Choropleth Map: Best Insurance Coverage

`r state.choropleth`

```{r, echo=FALSE}
# Create a choropleth map of each state that compares the average covered charges to the average total payments
library(zipcode)
library(choroplethr)
data(zipcode)
hospital.data.lat.lon <- hospital.data %>% 
  mutate(zip = paste(Provider.Zip.Code)) %>% 
  left_join(zipcode, by="zip")
source("scripts/getcounty.r")
counties <- hospital.data.lat.lon[, 17:16] %>% 
  filter(!is.na(latitude), !is.na(longitude)) %>% 
  latlong2county()
hospital.data.county <- hospital.data.lat.lon %>%
  filter(!is.na(latitude), !is.na(longitude))
data(county.fips)
hospital.data.county$county <- counties
hospital.data.counties <- hospital.data.county %>%
  select(Provider.City, county, Average.Covered.Charges, Average.Total.Payments) %>%  
  group_by(county) %>% 
  summarize(County.Covered.Charges = mean(as.numeric(gsub("\\$", "", Average.Covered.Charges)) / as.numeric(gsub("\\$", "", Average.Total.Payments)), na.rm = TRUE)) %>% 
  mutate(polyname = county) %>% 
  left_join(county.fips, by="polyname") %>% 
  mutate(value = County.Covered.Charges, region = fips) %>% 
  select(value, region)
county_choropleth(hospital.data.counties,
                 title      = "2012 Population Estimates",
                 legend     = "Population",
                 num_colors = 1
                 )
```
# County Choropleth Map: Best Insurance Coverage


