#
# This is the user-interface definition of a Shiny web application. You can
# run the application by clicking 'Run App' above.
#
# Find out more about building applications with Shiny here:
# 
#    http://shiny.rstudio.com/
#

library(shiny)
library(dplyr)
library(plotly)

shinyUI(fluidPage(
  titlePanel('City Hospital Information Filter'),
  sidebarLayout(
    sidebarPanel(
      selectInput('state.select', label  = 'State',
                  choices = list('Alabama' = 'AL', 
                                 "Alaska" = 'AK', 
                                 'Arizona' = 'AR',
                                 'Arkansas' = 'CA',
                                 'California' = 'CO',
                                 'Connecticut' = 'CT',
                                 'Washington D.C' = 'DC',
                                 'Delaware' = 'DE',
                                 'Florida' = 'FL',
                                 'Georgia' = 'GA',
                                 'Hawaii' = 'HI',
                                 'Idaho' = 'ID',
                                 'Illinois' = 'Il',
                                 'Indiana' = 'IN',
                                 'Iowa' = 'IA',
                                 'Kansas' = 'KS',
                                 'Kentucky' = 'KY',
                                 'Louisiana' = 'LA',
                                 'Maine' = 'ME',
                                 'Maryland' = 'MD',
                                 'Massachusetts' = 'MA',
                                 'Michigan' = 'MI',
                                 'Minnesota' = 'MN',
                                 'Mississippi' = 'MS',
                                 'Missouri' = 'MO',
                                 'Montana' = 'MT',
                                 'Nebraska' = 'NE',
                                 'Nevada' = 'NV',
                                 'New Hampshire' = 'NH',
                                 'New Jersey' = 'NH',
                                 'New Jersy' = 'NJ',
                                 'New Mexico' = 'NM',
                                 'New York' = 'NY',
                                 'North Carolina' = 'NC',
                                 'North Dakota' = 'ND',
                                 'Ohio' = 'OH',
                                 'Oklahoma' = 'OK',
                                 'Oregon' = 'OR',
                                 'Pennsylvania' = 'PA',
                                 'Rhode Island' = 'RI',
                                 'South Carolina' = 'SC',
                                 'South Dakota' = 'SD',
                                 'Tennessee' = 'TN',
                                 'Texas' = 'TX',
                                 'Utah' = 'UT',
                                 'Vermont' = 'VT',
                                 'Virginia' = 'VA',
                                 'Washington' = 'WA',
                                 'West Virginia' = 'WV',
                                 'Wisconsin' = 'WI',
                                 'Wyoming' = 'WY')),
     # selectInput('city.select', label = 'City',
      #            choices = tab3.data$Provider.City),
      selectInput('drg.select', label  = 'DRG: Diagnosis-Related Group',
                  choices = list(
                    '039 - EXTRACRANIAL PROCEDURES W/O CC/MCC' = '039 - EXTRACRANIAL PROCEDURES W/O CC/MCC', 
                    "057 - DEGENERATIVE NERVOUS SYSTEM DISORDERS W/O MCC" = '057 - DEGENERATIVE NERVOUS SYSTEM DISORDERS W/O MCC', 
                    "064 - INTRACRANIAL HEMORRHAGE OR CEREBRAL INFARCTION W MCC" = '064 - INTRACRANIAL HEMORRHAGE OR CEREBRAL INFARCTION W MCC', 
                    "065 - INTRACRANIAL HEMORRHAGE OR CEREBRAL INFARCTION W CC" = '065 - INTRACRANIAL HEMORRHAGE OR CEREBRAL INFARCTION W CC', 
                    "066 - INTRACRANIAL HEMORRHAGE OR CEREBRAL INFARCTION W/O CC/MCC" = '066 - INTRACRANIAL HEMORRHAGE OR CEREBRAL INFARCTION W/O CC/MCC', 
                    "069 - TRANSIENT ISCHEMIA" = '069 - TRANSIENT ISCHEMIA',
                    "074 - CRANIAL & PERIPHERAL NERVE DISORDERS W/O MCC" = '074 - CRANIAL & PERIPHERAL NERVE DISORDERS W/O MCC',
                    '101 - SEIZURES W/O MCC' = '101 - SEIZURES W/O MCC', 
                    "149 - DYSEQUILIBRIUM" = '149 - DYSEQUILIBRIUM',
                    '176 - PULMONARY EMBOLISM W/O MCC' = '176 - PULMONARY EMBOLISM W/O MCC',
                    "177 - RESPIRATORY INFECTIONS & INFLAMMATIONS W MCC" = '177 - RESPIRATORY INFECTIONS & INFLAMMATIONS W MCC', 
                    "178 - RESPIRATORY INFECTIONS & INFLAMMATIONS W CC" = '178 - RESPIRATORY INFECTIONS & INFLAMMATIONS W CC', 
                    '189 - PULMONARY EDEMA & RESPIRATORY FAILURE' = '189 - PULMONARY EDEMA & RESPIRATORY FAILURE',
                    "190 - CHRONIC OBSTRUCTIVE PULMONARY DISEASE W MCC" = '190 - CHRONIC OBSTRUCTIVE PULMONARY DISEASE W MCC',
                    '191 - CHRONIC OBSTRUCTIVE PULMONARY DISEASE W CC' = '191 - CHRONIC OBSTRUCTIVE PULMONARY DISEASE W CC',
                    "192 - CHRONIC OBSTRUCTIVE PULMONARY DISEASE W/O CC/MCC" = '192 - CHRONIC OBSTRUCTIVE PULMONARY DISEASE W/O CC/MCC', 
                    '193 - SIMPLE PNEUMONIA & PLEURISY W MCC' = '193 - SIMPLE PNEUMONIA & PLEURISY W MCC',
                    '194 - SIMPLE PNEUMONIA & PLEURISY W CC' = '194 - SIMPLE PNEUMONIA & PLEURISY W CC',
                    '195 - SIMPLE PNEUMONIA & PLEURISY W/O CC/MCC' = '195 - SIMPLE PNEUMONIA & PLEURISY W/O CC/MCC',
                    '202 - BRONCHITIS & ASTHMA W CC/MCC' = '202 - BRONCHITIS & ASTHMA W CC/MCC',
                    '203 - BRONCHITIS & ASTHMA W/O CC/MCC' = '203 - BRONCHITIS & ASTHMA W/O CC/MCC',
                    '207 - RESPIRATORY SYSTEM DIAGNOSIS W VENTILATOR SUPPORT 96+ HOURS' = '207 - RESPIRATORY SYSTEM DIAGNOSIS W VENTILATOR SUPPORT 96+ HOURS',
                    '208 - RESPIRATORY SYSTEM DIAGNOSIS W VENTILATOR SUPPORT <96 HOURS' = '208 - RESPIRATORY SYSTEM DIAGNOSIS W VENTILATOR SUPPORT <96 HOURS',
                    '238 - MAJOR CARDIOVASC PROCEDURES W/O MCC' = '238 - MAJOR CARDIOVASC PROCEDURES W/O MCC',
                    '243 - PERMANENT CARDIAC PACEMAKER IMPLANT W CC' = '243 - PERMANENT CARDIAC PACEMAKER IMPLANT W CC',
                    '244 - PERMANENT CARDIAC PACEMAKER IMPLANT W/O CC/MCC' = '244 - PERMANENT CARDIAC PACEMAKER IMPLANT W/O CC/MCC',
                    '246 - PERC CARDIOVASC PROC W DRUG-ELUTING STENT W MCC OR 4+ VESSELS/STENTS' = '246 - PERC CARDIOVASC PROC W DRUG-ELUTING STENT W MCC OR 4+ VESSELS/STENTS',
                    '247 - PERC CARDIOVASC PROC W DRUG-ELUTING STENT W/O MCC' = '247 - PERC CARDIOVASC PROC W DRUG-ELUTING STENT W/O MCC',
                    '249 - PERC CARDIOVASC PROC W NON-DRUG-ELUTING STENT W/O MCC' = '249 - PERC CARDIOVASC PROC W NON-DRUG-ELUTING STENT W/O MCC',
                    '251 - PERC CARDIOVASC PROC W/O CORONARY ARTERY STENT W/O MCC' = '251 - PERC CARDIOVASC PROC W/O CORONARY ARTERY STENT W/O MCC',
                    '252 - OTHER VASCULAR PROCEDURES W MCC' = '252 - OTHER VASCULAR PROCEDURES W MCC',
                    '253 - OTHER VASCULAR PROCEDURES W CC' = '253 - OTHER VASCULAR PROCEDURES W CC',
                    '254 - OTHER VASCULAR PROCEDURES W/O CC/MCC' = '254 - OTHER VASCULAR PROCEDURES W/O CC/MCC',
                    '280 - ACUTE MYOCARDIAL INFARCTION, DISCHARGED ALIVE W MCC' = '280 - ACUTE MYOCARDIAL INFARCTION, DISCHARGED ALIVE W MCC',
                    '281 - ACUTE MYOCARDIAL INFARCTION, DISCHARGED ALIVE W CC' = '281 - ACUTE MYOCARDIAL INFARCTION, DISCHARGED ALIVE W CC',
                    '282 - ACUTE MYOCARDIAL INFARCTION, DISCHARGED ALIVE W/O CC/MCC' = '282 - ACUTE MYOCARDIAL INFARCTION, DISCHARGED ALIVE W/O CC/MCC',
                    '286 - CIRCULATORY DISORDERS EXCEPT AMI, W CARD CATH W MCC' = '286 - CIRCULATORY DISORDERS EXCEPT AMI, W CARD CATH W MCC',
                    '287 - CIRCULATORY DISORDERS EXCEPT AMI, W CARD CATH W/O MCC' = '287 - CIRCULATORY DISORDERS EXCEPT AMI, W CARD CATH W/O MCC',
                    '291 - HEART FAILURE & SHOCK W MCC' = '291 - HEART FAILURE & SHOCK W MCC',
                    '292 - HEART FAILURE & SHOCK W CC' = '292 - HEART FAILURE & SHOCK W CC',
                    '293 - HEART FAILURE & SHOCK W/O CC/MCC' = '293 - HEART FAILURE & SHOCK W/O CC/MCC',
                    '300 - PERIPHERAL VASCULAR DISORDERS W CC' = '300 - PERIPHERAL VASCULAR DISORDERS W CC',
                    '301 - PERIPHERAL VASCULAR DISORDERS W/O CC/MCC' = '301 - PERIPHERAL VASCULAR DISORDERS W/O CC/MCC',
                    '303 - ATHEROSCLEROSIS W/O MCC' = '303 - ATHEROSCLEROSIS W/O MCC',
                    '305 - HYPERTENSION W/O MCC' = '305 - HYPERTENSION W/O MCC',
                    '308 - CARDIAC ARRHYTHMIA & CONDUCTION DISORDERS W MCC' = '308 - CARDIAC ARRHYTHMIA & CONDUCTION DISORDERS W MCC',
                    '309 - CARDIAC ARRHYTHMIA & CONDUCTION DISORDERS W CC' = '309 - CARDIAC ARRHYTHMIA & CONDUCTION DISORDERS W CC',
                    '310 - CARDIAC ARRHYTHMIA & CONDUCTION DISORDERS W/O CC/MCC' = '310 - CARDIAC ARRHYTHMIA & CONDUCTION DISORDERS W/O CC/MCC',
                    '312 - SYNCOPE & COLLAPSE' = '312 - SYNCOPE & COLLAPSE',
                    '313 - CHEST PAIN' = '313 - CHEST PAIN',
                    '314 - OTHER CIRCULATORY SYSTEM DIAGNOSES W MCC' = '314 - OTHER CIRCULATORY SYSTEM DIAGNOSES W MCC',
                    '315 - OTHER CIRCULATORY SYSTEM DIAGNOSES W CC' = '315 - OTHER CIRCULATORY SYSTEM DIAGNOSES W CC',
                    '329 - MAJOR SMALL & LARGE BOWEL PROCEDURES W MCC' = '329 - MAJOR SMALL & LARGE BOWEL PROCEDURES W MCC',
                    '330 - MAJOR SMALL & LARGE BOWEL PROCEDURES W CC' = '330 - MAJOR SMALL & LARGE BOWEL PROCEDURES W CC',
                    '372 - MAJOR GASTROINTESTINAL DISORDERS & PERITONEAL INFECTIONS W CC' = '372 - MAJOR GASTROINTESTINAL DISORDERS & PERITONEAL INFECTIONS W CC',
                    '377 - G.I. HEMORRHAGE W MCC' = '377 - G.I. HEMORRHAGE W MCC',
                    '378 - G.I. HEMORRHAGE W CC' = '378 - G.I. HEMORRHAGE W CC',
                    '379 - G.I. HEMORRHAGE W/O CC/MCC' = '379 - G.I. HEMORRHAGE W/O CC/MCC',
                    '389 - G.I. OBSTRUCTION W CC' = '389 - G.I. OBSTRUCTION W CC',
                    '390 - G.I. OBSTRUCTION W/O CC/MCC' = '390 - G.I. OBSTRUCTION W/O CC/MCC',
                    '391 - ESOPHAGITIS, GASTROENT & MISC DIGEST DISORDERS W MCC' = '391 - ESOPHAGITIS, GASTROENT & MISC DIGEST DISORDERS W MCC',
                    '392 - ESOPHAGITIS, GASTROENT & MISC DIGEST DISORDERS W/O MCC' = '392 - ESOPHAGITIS, GASTROENT & MISC DIGEST DISORDERS W/O MCC',
                    '394 - OTHER DIGESTIVE SYSTEM DIAGNOSES W CC' = '394 - OTHER DIGESTIVE SYSTEM DIAGNOSES W CC',
                    '418 - LAPAROSCOPIC CHOLECYSTECTOMY W/O C.D.E. W CC' = '418 - LAPAROSCOPIC CHOLECYSTECTOMY W/O C.D.E. W CC',
                    '419 - LAPAROSCOPIC CHOLECYSTECTOMY W/O C.D.E. W/O CC/MCC' = '419 - LAPAROSCOPIC CHOLECYSTECTOMY W/O C.D.E. W/O CC/MCC',
                    '439 - DISORDERS OF PANCREAS EXCEPT MALIGNANCY W CC' = '439 - DISORDERS OF PANCREAS EXCEPT MALIGNANCY W CC',
                    '460 - SPINAL FUSION EXCEPT CERVICAL W/O MCC' = '460 - SPINAL FUSION EXCEPT CERVICAL W/O MCC',
                    '469 - MAJOR JOINT REPLACEMENT OR REATTACHMENT OF LOWER EXTREMITY W MCC' = '469 - MAJOR JOINT REPLACEMENT OR REATTACHMENT OF LOWER EXTREMITY W MCC',
                    '470 - MAJOR JOINT REPLACEMENT OR REATTACHMENT OF LOWER EXTREMITY W/O MCC' = '470 - MAJOR JOINT REPLACEMENT OR REATTACHMENT OF LOWER EXTREMITY W/O MCC',
                    '473 - CERVICAL SPINAL FUSION W/O CC/MCC' = '473 - CERVICAL SPINAL FUSION W/O CC/MCC',
                    '480 - HIP & FEMUR PROCEDURES EXCEPT MAJOR JOINT W MCC' = '480 - HIP & FEMUR PROCEDURES EXCEPT MAJOR JOINT W MCC',
                    '481 - HIP & FEMUR PROCEDURES EXCEPT MAJOR JOINT W CC' = '481 - HIP & FEMUR PROCEDURES EXCEPT MAJOR JOINT W CC',
                    '482 - HIP & FEMUR PROCEDURES EXCEPT MAJOR JOINT W/O CC/MCC' = '482 - HIP & FEMUR PROCEDURES EXCEPT MAJOR JOINT W/O CC/MCC',
                    '491 - BACK & NECK PROC EXC SPINAL FUSION W/O CC/MCC' = '491 - BACK & NECK PROC EXC SPINAL FUSION W/O CC/MCC',
                    '536 - FRACTURES OF HIP & PELVIS W/O MCC' = '536 - FRACTURES OF HIP & PELVIS W/O MCC',
                    '552 - MEDICAL BACK PROBLEMS W/O MCC' = '552 - MEDICAL BACK PROBLEMS W/O MCC',
                    '563 - FX, SPRN, STRN & DISL EXCEPT FEMUR, HIP, PELVIS & THIGH W/O MCC' = '563 - FX, SPRN, STRN & DISL EXCEPT FEMUR, HIP, PELVIS & THIGH W/O MCC',
                    '602 - CELLULITIS W MCC' = '602 - CELLULITIS W MCC',
                    '603 - CELLULITIS W/O MCC' = '603 - CELLULITIS W/O MCC',
                    '638 - DIABETES W CC' = '638 - DIABETES W CC',
                    '640 - MISC DISORDERS OF NUTRITION,METABOLISM,FLUIDS/ELECTROLYTES W MCC' = '640 - MISC DISORDERS OF NUTRITION,METABOLISM,FLUIDS/ELECTROLYTES W MCC',
                    '641 - MISC DISORDERS OF NUTRITION,METABOLISM,FLUIDS/ELECTROLYTES W/O MCC' = '641 - MISC DISORDERS OF NUTRITION,METABOLISM,FLUIDS/ELECTROLYTES W/O MCC',
                    '682 - RENAL FAILURE W MCC' = '682 - RENAL FAILURE W MCC',
                    '683 - RENAL FAILURE W CC' = '683 - RENAL FAILURE W CC',
                    '684 - RENAL FAILURE W/O CC/MCC' = '684 - RENAL FAILURE W/O CC/MCC',
                    '689 - KIDNEY & URINARY TRACT INFECTIONS W MCC' = '689 - KIDNEY & URINARY TRACT INFECTIONS W MCC',
                    '690 - KIDNEY & URINARY TRACT INFECTIONS W/O MCC' = '690 - KIDNEY & URINARY TRACT INFECTIONS W/O MCC',
                    '698 - OTHER KIDNEY & URINARY TRACT DIAGNOSES W MCC' = '698 - OTHER KIDNEY & URINARY TRACT DIAGNOSES W MCC',
                    '699 - OTHER KIDNEY & URINARY TRACT DIAGNOSES W CC' = '699 - OTHER KIDNEY & URINARY TRACT DIAGNOSES W CC',
                    '811 - RED BLOOD CELL DISORDERS W MCC' = '811 - RED BLOOD CELL DISORDERS W MCC',
                    '812 - RED BLOOD CELL DISORDERS W/O MCC' = '812 - RED BLOOD CELL DISORDERS W/O MCC',
                    '853 - INFECTIOUS & PARASITIC DISEASES W O.R. PROCEDURE W MCC' = '853 - INFECTIOUS & PARASITIC DISEASES W O.R. PROCEDURE W MCC',
                    '870 - SEPTICEMIA OR SEVERE SEPSIS W MV 96+ HOURS' = '870 - SEPTICEMIA OR SEVERE SEPSIS W MV 96+ HOURS',
                    '871 - SEPTICEMIA OR SEVERE SEPSIS W/O MV 96+ HOURS W MCC' = '871 - SEPTICEMIA OR SEVERE SEPSIS W/O MV 96+ HOURS W MCC',
                    '872 - SEPTICEMIA OR SEVERE SEPSIS W/O MV 96+ HOURS W/O MCC' = '872 - SEPTICEMIA OR SEVERE SEPSIS W/O MV 96+ HOURS W/O MCC',
                    '885 - PSYCHOSES' = '885 - PSYCHOSES',
                    '897 - ALCOHOL/DRUG ABUSE OR DEPENDENCE W/O REHABILITATION THERAPY W/O MCC' = '897 - ALCOHOL/DRUG ABUSE OR DEPENDENCE W/O REHABILITATION THERAPY W/O MCC',
                    '917 - POISONING & TOXIC EFFECTS OF DRUGS W MCC' = '917 - POISONING & TOXIC EFFECTS OF DRUGS W MCC',
                    '918 - POISONING & TOXIC EFFECTS OF DRUGS W/O MCC' = '918 - POISONING & TOXIC EFFECTS OF DRUGS W/O MCC',
                    '948 - SIGNS & SYMPTOMS W/O MCC' = '948 - SIGNS & SYMPTOMS W/O MCC'))
    ),
    mainPanel(
      plotlyOutput('bar.chart.city.info')
    )
  ))
)




